### PR TITLE
"Added initial prefix on rowId"

### PR DESCRIPTION
**Pull request by agwells0714**

### CODE REVIEW

**Comment by cjmay** [comment]
Is this PR still under consideration?  I need a prefix range if I'm to use pyaccumulo in my current project (and I would like to).

**Comment by johnrfrank** [comment]
Hi @cjmay,  I haven't touched this code in quite a while.  Can you confirm that all tests pass?  It requires an accumulo instance to test it.

**Comment by cjmay** [comment]
Ok.  Do you anticipate any further development in the future?

All (55) tests pass on my end.  There was one warning:

```
WI1 /home/hltcoe/cmay/.local/lib/python2.7/site-packages/pytest_capturelog.py:171 'pytest_runtest_makereport' hook uses deprecated __multicall__ argument
```

If you like I created another pull request, #26, that merges this branch into master, adds tests for followingPrefix and prefix, and fixes an indentation error.

**Comment by johnrfrank** [comment]
@cjmay   -- let me know if that provides what you need, and thanks for testing it!   If there is an interest in active development on this, we can discuss re-enabling the auto build & test infrastructure we were providing.

**Pull request merged**
